config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "categories#index"

  resources :categories do
    resources :lessons do
      member do
        patch 'create_bundle'
        patch 'continue_create_bundle'
      end
    end
    member do
      get 'translate_me/all', to: 'translate_me_game#all', as: :translate_me_all
      get 'translate_me/:lesson_number', to: 'translate_me_game#translate', as: :translate_me
      get 'dictionary/all'
      get 'dictionary/:letter', to: 'dictionary#letter', as: :dictionary
      get 'part_of_speech/:part_of_speech', to: 'dictionary#part_of_speech', as: :part_of_speech
    end
  end

  resources :lessons do
    resources :entities
    post 'unknown/:word', to: 'dictionary#unknown', as: :unknown
    post 'known/:word', to: 'dictionary#known', as: :known
  end

  resources :tags do
    member do
      get 'translate', to: 'tags#translate', as: :translate
    end
  end

  delete 'entities/:entity_id/tags/:id', to: 'dictionary#remove_tag', as: :entity_tag

  get 'search', to: 'search#find_words'

  get 'search_autocomplete', to: 'search#autocomplete_entity_word'

  get 'next_lesson/categories/:category_id//lessons_numbers/:lesson_number', to: 'change_lesson#next', as: :next_lesson
  get 'previous_lesson/categories/:category_id/lessons_numbers/:lesson_number', to: 'change_lesson#previous', as: :previous_lesson

  get 'next_translate_me/categories/:category_id/lessons_numbers/:lesson_number', to: 'change_translate_me#next', as: :next_translate_me
  get 'previous_translate_me/categories/:category_id/lessons_numbers/:lesson_number', to: 'change_translate_me#previous', as: :previous_translate_me

  get 'dictionary/all_words', to: 'dictionary#all_words', as: :dictionary_all
  get 'dictionary/:letter', to: 'dictionary#all_letters', as: :dictionary

  get 'part_of_speech/:part_of_speech', to: 'dictionary#all_part_of_speech', as: :part_of_speech

  get 'word/:word', to: 'dictionary#word', as: :word

end

app/views/shared/_bottom_bar.html.haml
%span#bottom_bar
  - if params[:controller] == 'lessons'
    %b Lessons:
    - @all_lessons.each do |l|
      = link_to l.number, category_lesson_path(@category, l)
  - elsif params[:controller] == 'translate_me_game'
    %b Games:
    - @all_lessons.each do |l|
      = link_to l.number, translate_me_category_path(@category, l.number)

app/views/shared/_errors.html.haml
- if !@object.nil? && @object.errors.any?
  #error_explanation
    %h2= "Please correct the following #{pluralize(@object.errors.count, "error")}:"
    %ul
      - @object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_footer.html.haml
%footer
  .container
    %center
      2015 by 2husher

app/views/shared/_games.html.haml
= link_to 'All Games', translate_me_all_category_path(@category)

app/views/shared/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      %nav
        %ul.nav
          %li= link_to 'Categories', categories_path
          - if @category.present?
            %li= link_to 'Words', dictionary_all_category_path(@category)
          - else
            %li= link_to 'All Words', dictionary_all_path
          - if @category.present?
            %li= link_to 'Lessons', category_lessons_path(@category)
            %li= link_to 'Translate Me', translate_me_all_category_path(@category)
          - unless user_signed_in?
            %li= link_to 'Sign in', new_user_session_path
            -#%li= link_to 'Sign up', new_user_registration_path
          - else
            %li= link_to 'All Tags', tags_path
            %li= link_to 'Sign out', destroy_user_session_path, method: :delete

app/views/shared/_lessons.html.haml
= link_to 'All Lessons', category_lessons_path(@category)
- if user_signed_in?
  = link_to 'Add New Lesson', new_category_lesson_path(@category, @category.lessons.build)
  = render 'lessons/new'

app/views/shared/_letters.html.haml
%center
  %span#all_letters
  - if @category.present?
    = link_to 'All Letters', dictionary_all_category_path(@category)
  - else
    = link_to 'All Letters', dictionary_all_path

  - Letter.all.each do |l|
    - if @category.present?
      = link_to l.name, dictionary_category_path(@category, l.name)
    - else
      = link_to l.name, dictionary_path(l.name)

%center
  %span#part_of_speech
  - PartOfSpeech.all.each do |pos|
    - if @category.present?
      = link_to pos.name, part_of_speech_category_path(@category, pos.name)
    - else
      = link_to pos.name, part_of_speech_path(pos.name)

app/views/shared/_search.html.haml
= form_tag("/search", method: "get", enforce_utf8: false) do
  = label_tag(:search, "Search for:")
  = autocomplete_field_tag :search, '', search_autocomplete_path
  = submit_tag("Search")

app/views/shared/_sidebar.html.haml
- if params[:controller] == 'dictionary'
  %h1 Dictionary
  = render 'shared/letters'
- elsif params[:controller] == 'lessons'
  %h1 Lessons
  Hide translation #{check_box_tag 'hide_transl', 'hide translations', true}
  = render 'shared/lessons'

app/views/shared/_top_bar.html.haml
= render 'shared/search'

- if params[:controller] == 'dictionary'
  %h1
    Words
    - if !@entities.nil? && @entities.count > 2
      #{@entities.first.word} - #{@entities.last.word}
  = render 'shared/letters'
- elsif params[:controller] == 'lessons'
  %h1
    Lessons
    - if !@lessons.nil? && @lessons.count > 2
      #{@lessons.first.number} - #{@lessons.last.number}
  = render 'shared/lessons'
- elsif params[:controller] == 'translate_me_game'
  %h1
    Translate Me
    - if !@lessons.nil? && @lessons.count > 2
      #{@lessons.first.number} - #{@lessons.last.number}
  = render 'shared/games'
- elsif params[:controller] == 'search'
  %h1
    Results for #{params[:search]}