config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "categories#index"

  resources :categories do
    resources :lessons do
      member do
        patch 'create_bundle'
        patch 'continue_create_bundle'
      end
    end
    member do
      get 'translate_me/all', to: 'translate_me_game#all', as: :translate_me_all
      get 'translate_me/:lesson_number', to: 'translate_me_game#translate', as: :translate_me
      get 'dictionary/all'
      get 'dictionary/:letter', to: 'dictionary#letter', as: :dictionary
      get 'part_of_speech/:part_of_speech', to: 'dictionary#part_of_speech', as: :part_of_speech
    end
  end

  resources :lessons do
    resources :entities
    post 'unknown/:word', to: 'dictionary#unknown', as: :unknown
    post 'known/:word', to: 'dictionary#known', as: :known
  end

  resources :tags do
    member do
      get 'translate', to: 'tags#translate', as: :translate
    end
  end

  delete 'entities/:entity_id/tags/:id', to: 'dictionary#remove_tag', as: :entity_tag

  get 'search', to: 'search#find_words'

  get 'search_autocomplete', to: 'search#autocomplete_entity_word'

  get 'next_lesson/categories/:category_id//lessons_numbers/:lesson_number', to: 'change_lesson#next', as: :next_lesson
  get 'previous_lesson/categories/:category_id/lessons_numbers/:lesson_number', to: 'change_lesson#previous', as: :previous_lesson

  get 'next_translate_me/categories/:category_id/lessons_numbers/:lesson_number', to: 'change_translate_me#next', as: :next_translate_me
  get 'previous_translate_me/categories/:category_id/lessons_numbers/:lesson_number', to: 'change_translate_me#previous', as: :previous_translate_me

  get 'dictionary/all_words', to: 'dictionary#all_words', as: :dictionary_all
  get 'dictionary/:letter', to: 'dictionary#all_letters', as: :dictionary

  get 'part_of_speech/:part_of_speech', to: 'dictionary#all_part_of_speech', as: :part_of_speech

  get 'word/:word', to: 'dictionary#word', as: :word

end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id   :integer          not null, primary key
#  name :string
#

class Tag < ActiveRecord::Base
  has_many :labels
  has_many :users, through: :labels

  validates :name, presence: true

  def show_entities(user)
    label = Label.where("user_id = ? and tag_id = ?", user.id, self.id).first
    label.entities
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @tags = Tag.paginate(page: params[:page], per_page: 20)
  end

  def show
    tag = Tag.find_by(id: params[:id])
    @tag_entities = tag.show_entities(current_user).paginate(page: params[:page], per_page: 20)
  end

  def translate
    @tag = Tag.find_by(id: params[:id])
    @tag_entities = []
    @tag.show_entities(current_user).each do |e|
      tmp    = []
      tmp[0] = e.word
      tmp[1] = e.translation
      tmp[2] = e.sentence
      tmp[3] = e.all_tags(current_user) if current_user.present?
      @tag_entities << tmp
    end
    @tag_entities.shuffle!
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_tag.html.haml
%span.tag= tag

app/views/tags/index.html.haml
- @tags.each do |tag|
  %div{class: "tag #{cycle('line_odd', 'line_even')}" }
    = link_to tag.name, tag_path(tag)
    &lt;
    = link_to "Translate #{tag.name} tag", translate_tag_path(tag)
    &gt;

app/views/tags/show.html.haml
= render @tag_entities

= will_paginate @tag_entities

app/views/tags/translate.html.haml
%h3
  = link_to "Translate #{@tag.name}", translate_tag_path(@tag)
  for
  = link_to "#{@tag.name}", tag_path(@tag)

%button{id: 'all_at_once', type:"button", class:"btn"} All At Once
%button{id: 'by_one', type:"button", class:"btn"} By One
%button{id: 'next_one', type:"button", class:"btn", style: "display: none;"} Next One

- @tag_entities.each do |e|
  %div{class: "entity #{cycle('line_odd', 'line_even')}" }
    %span.word= e[0]
    %span.translation{style: 'display: none;'}
      = e[1]
    %span.sentence{style: 'display: none;'}
      = e[2]

%hr
%button{id: 'translate_me', type:"button", class:"btn btn-danger"} Translate!
%button{id: 'show_sentence', type:"button", class:"btn btn-success"} Sentence