config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "categories#index"

  resources :categories do
    resources :lessons do
      member do
        patch 'create_bundle'
        patch 'continue_create_bundle'
      end
    end
    member do
      get 'translate_me/all', to: 'translate_me_game#all', as: :translate_me_all
      get 'translate_me/:lesson_number', to: 'translate_me_game#translate', as: :translate_me
      get 'dictionary/all'
      get 'dictionary/:letter', to: 'dictionary#letter', as: :dictionary
      get 'part_of_speech/:part_of_speech', to: 'dictionary#part_of_speech', as: :part_of_speech
    end
  end

  resources :lessons do
    resources :entities
    post 'unknown/:word', to: 'dictionary#unknown', as: :unknown
    post 'known/:word', to: 'dictionary#known', as: :known
  end

  resources :tags do
    member do
      get 'translate', to: 'tags#translate', as: :translate
    end
  end

  delete 'entities/:entity_id/tags/:id', to: 'dictionary#remove_tag', as: :entity_tag

  get 'search', to: 'search#find_words'

  get 'search_autocomplete', to: 'search#autocomplete_entity_word'

  get 'next_lesson/categories/:category_id//lessons_numbers/:lesson_number', to: 'change_lesson#next', as: :next_lesson
  get 'previous_lesson/categories/:category_id/lessons_numbers/:lesson_number', to: 'change_lesson#previous', as: :previous_lesson

  get 'next_translate_me/categories/:category_id/lessons_numbers/:lesson_number', to: 'change_translate_me#next', as: :next_translate_me
  get 'previous_translate_me/categories/:category_id/lessons_numbers/:lesson_number', to: 'change_translate_me#previous', as: :previous_translate_me

  get 'dictionary/all_words', to: 'dictionary#all_words', as: :dictionary_all
  get 'dictionary/:letter', to: 'dictionary#all_letters', as: :dictionary

  get 'part_of_speech/:part_of_speech', to: 'dictionary#all_part_of_speech', as: :part_of_speech

  get 'word/:word', to: 'dictionary#word', as: :word

end

app/models/lesson.rb
# == Schema Information
#
# Table name: lessons
#
#  id          :integer          not null, primary key
#  number      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#

class Lesson < ActiveRecord::Base
  attr_accessor :bundle

  has_many :entities
  belongs_to :category

  validates :number, presence: true#, uniqueness: true
  validates :category_id, presence: true

  def entity_attributes=(entity_attributes)
    p "HEEEEEEEEEERRRRRRRRRRRREEEEEEEEEEEE"
    entity_attributes.each do |attributes|
      part_of_speech = PartOfSpeech.find_by(acronym: attributes[:part_of_speech])
      p part_of_speech
      attributes.merge!(part_of_speech: part_of_speech)
      p attributes
      p "PartOfSpeech #{attributes[:part_of_speech]}"
      new_entity = entities.build(attributes)
      word = attributes[:word]
      letter = word[0].upcase if word.present?
      new_entity.letter = Letter.find_by(name: letter)
      new_entity.save!
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @category    = Category.find(params[:category_id])
    #@lessons  = @category.lessons.includes(:entities).all
    @all_lessons = @category.lessons.all
    @lesson_number = @all_lessons.present? ? @all_lessons.maximum(:number) + 1 : 1
    @lessons     = @all_lessons.paginate(page: params[:page], per_page: max_entities_per_lesson)
    @new_lesson      = @category.lessons.new
  end

  def show
    @category = Category.find(params[:category_id])
    @all_lessons = @category.lessons.all
    @lesson      = @all_lessons.find(params[:id])
    # without all @entities processed at form and include nill new entity
    @entities = @lesson.entities.all
    @new_lesson      = @category.lessons.new
    @new_entity      = @entities.new
  end

  def create
    @category = Category.find(params[:category_id])
    @lesson   = @category.lessons.build(lesson_params)
    if @lesson.save
      respond_to do |format|
        format.html do
          redirect_to [@category, @lesson], notice: 'Lesson created'
        end
      end
    else
      respond_to do |format|
        format.html do
          flash[:error] = 'Wrong params for lesson'
          redirect_to category_lessons_path(@category)
        end
      end
    end
  end

  def update
    @category = Category.find(params[:category_id])
    @lesson   = @category.lessons.find(params[:id])
    if @lesson.update(lesson_params)
      redirect_to [@category, @lesson]
    end
  end

  def create_bundle
    @category = Category.find(params[:category_id])
    @lesson   = @category.lessons.find(params[:id])
    @all_lessons = @category.lessons.all
    @new_lesson      = @category.lessons.new
    bundle = params[:lesson][:bundle]
    p bundle
    bundle_split = bundle.split(/(.+)\s+\[(\w+)\]\s+(.+)\s+\[.*\]\s+(.+)\n/)
    @entities = []
    bundle_split.each_slice(5) do |x|
      entity = {}
      entity[:translation] = x[1]
      entity[:pos] = x[2]
      entity[:word] = x[3]
      entity[:sentence] = x[4]
      letter = entity[:word].upcase if entity[:word].present?
      entity[:letter] = Letter.find_by(name: letter)
      @entities << entity
    end
    @entities.size.times{ @lesson.entities.build }
  end

  def continue_create_bundle
  end

  private
    def lesson_params
      params.require(:lesson).permit(:number, entity_attributes: [:word, :translation, :sentence, :part_of_speech])
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
  def first_lesson?(category, lesson_num)
    @category = Category.find(category.id)
    min_num   = @category.lessons.minimum(:number)
    return true if lesson_num <= min_num
    return false
  end

  def last_lesson?(category, lesson_num)
    @category = Category.find(category.id)
    max_num   = @category.lessons.maximum("number")
    return true if lesson_num >= max_num
    return false
  end
end

app/views/lessons/_bundle_entity.html.haml
%div{class: "entity #{cycle('line_odd', 'line_even')}" }
  %span.word= bundle_entity[:word]
  %span.part_of_speech= bundle_entity[:part_of_speech]
  %span.translation= bundle_entity[:translation]
  %span.sentence= bundle_entity[:sentence]

app/views/lessons/_form.html.haml
= form_for [@category, @new_lesson] do |f|
  %table
    %tr
      %td= f.label :number
      %td= f.text_field :number, value: lesson_number
  .actions
    = f.submit @new_lesson.new_record? ? 'Create Lesson' : 'Update Lesson'

app/views/lessons/_lesson.html.haml
%div{class: "lesson #{cycle('line_odd', 'line_even')}" }
  %span.lesson_num
    = link_to "Lesson #{lesson.number}", category_lesson_path(@category, lesson)
  %span.translate_me
    &lt;#{link_to 'Translate Me Game', translate_me_category_path(@category, lesson.number)}&gt;
  %span.words
  - lesson.entities.each do |e|
    %span.word= e.word

app/views/lessons/_new.html.haml
= render partial: 'form', locals: { lesson_number: @lesson_number }

app/views/lessons/all.html.haml
= render @lessons

= will_paginate @lessons

app/views/lessons/create_bundle.html.haml
%h3 Check the result of parsing


-#= render partial: "bundle_entity", collection: @entities
= render 'entities/new_entities'

= link_to "OK", '#'
= link_to "Back", [@category, @lesson]

app/views/lessons/index.html.haml
= render @lessons

= will_paginate @lessons

app/views/lessons/show.html.haml
- unless first_lesson?(@category, @lesson.number)
  = link_to 'Previous', previous_lesson_path(@category, @lesson.number)
- unless last_lesson?(@category, @lesson.number)
  = link_to 'Next', next_lesson_path(@category, @lesson.number)

%h3
  Lesson #{@lesson.number}
  &lt;#{link_to 'Translate Me Game', translate_me_category_path(@category, @lesson.number)}&gt;

- if user_signed_in? && (@lesson.entities.count < max_entities_per_lesson)
  = render 'entities/new'
  = render 'entities/new_bundle'

= render @entities