config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "categories#index"

  resources :categories do
    resources :lessons do
      member do
        patch 'create_bundle'
        patch 'continue_create_bundle'
      end
    end
    member do
      get 'translate_me/all', to: 'translate_me_game#all', as: :translate_me_all
      get 'translate_me/:lesson_number', to: 'translate_me_game#translate', as: :translate_me
      get 'dictionary/all'
      get 'dictionary/:letter', to: 'dictionary#letter', as: :dictionary
      get 'part_of_speech/:part_of_speech', to: 'dictionary#part_of_speech', as: :part_of_speech
    end
  end

  resources :lessons do
    resources :entities
    post 'unknown/:word', to: 'dictionary#unknown', as: :unknown
    post 'known/:word', to: 'dictionary#known', as: :known
  end

  resources :tags do
    member do
      get 'translate', to: 'tags#translate', as: :translate
    end
  end

  delete 'entities/:entity_id/tags/:id', to: 'dictionary#remove_tag', as: :entity_tag

  get 'search', to: 'search#find_words'

  get 'search_autocomplete', to: 'search#autocomplete_entity_word'

  get 'next_lesson/categories/:category_id//lessons_numbers/:lesson_number', to: 'change_lesson#next', as: :next_lesson
  get 'previous_lesson/categories/:category_id/lessons_numbers/:lesson_number', to: 'change_lesson#previous', as: :previous_lesson

  get 'next_translate_me/categories/:category_id/lessons_numbers/:lesson_number', to: 'change_translate_me#next', as: :next_translate_me
  get 'previous_translate_me/categories/:category_id/lessons_numbers/:lesson_number', to: 'change_translate_me#previous', as: :previous_translate_me

  get 'dictionary/all_words', to: 'dictionary#all_words', as: :dictionary_all
  get 'dictionary/:letter', to: 'dictionary#all_letters', as: :dictionary

  get 'part_of_speech/:part_of_speech', to: 'dictionary#all_part_of_speech', as: :part_of_speech

  get 'word/:word', to: 'dictionary#word', as: :word

end

app/controllers/translate_me_game_controller.rb
class TranslateMeGameController < ApplicationController
  def all
    @category = Category.find(params[:id])
    #@lessons  = @category.lessons.includes(:entities)
    @all_lessons = @category.lessons
    @lessons     = @all_lessons.paginate(page: params[:page], per_page: max_entities_per_lesson)
  end

  def translate
    @category = Category.find(params[:id])
    @all_lessons  = @category.lessons
    @lesson = @all_lessons.find_by(number: params[:lesson_number])
    @entities_array = []
    @lesson.entities.each do |e|
      tmp    = []
      tmp[0] = e.word
      tmp[1] = e.translation
      tmp[2] = e.sentence
      tmp[3] = e.all_tags(current_user) if current_user.present?
      @entities_array << tmp
    end
    # TODO: is @entities_array available in js?
    @entities_array.shuffle!
  end
end

app/views/translate_me_game/_lesson.html.haml
%div{class: "lesson #{cycle('line_odd', 'line_even')}" }
  %span.translate_me
    = link_to 'Translate Me Game', translate_me_category_path(@category, lesson.number)
  for
  %span.lesson_num
    = link_to "Lesson #{lesson.number}", category_lesson_path(@category, lesson)
  %span.words
    - lesson.entities.each do |e|
      %span.word= e.word

app/views/translate_me_game/all.html.haml
= render partial: 'lesson', collection: @lessons

= will_paginate @lessons

app/views/translate_me_game/translate.html.haml
- unless first_lesson?(@category, @lesson.number)
  = link_to 'Previous', previous_translate_me_path(@category, @lesson.number)
- unless last_lesson?(@category, @lesson.number)
  = link_to 'Next', next_translate_me_path(@category, @lesson.number)

%h3
  = link_to "Game", translate_me_category_path(@category, @lesson.number)
  for
  = link_to "Lesson #{@lesson.number}", category_lesson_path(@category, @lesson)

%button{id: 'all_at_once', type:"button", class:"btn"} All At Once
%button{id: 'by_one', type:"button", class:"btn"} By One
%button{id: 'next_one', type:"button", class:"btn", style: "display: none;"} Next One

- @entities_array.each do |e|
  %div{class: "entity #{cycle('line_odd', 'line_even')}" }
    %span.word= e[0]
    - if user_signed_in?
      = button_to "Know",                                      |
                  lesson_known_path(@lesson, e[0]),            |
                  remote: true
      = button_to "Don't know",                                |
                  lesson_unknown_path(@lesson, e[0]),          |
                  remote: true
    - if user_signed_in?
      %span.tags= render partial: 'tags/tag', collection: e[3]
    %span.translation{style: 'display: none;'}
      = e[1]
    %span.sentence{style: 'display: none;'}
      = e[2]

%hr
%button{id: 'translate_me', type:"button", class:"btn btn-danger"} Translate!
%button{id: 'show_sentence', type:"button", class:"btn btn-success"} Sentence